[package]
name = "util_settings"
version = "0.1.0"
authors = ["Kevin Hill <kah.kevin.hill@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
envconf = "0.1.1"
